name: All

on:
  push:
  pull_request:

jobs:
  all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Source code styling
        run: |
          brew install ktfmt
          make style
          git diff --exit-code
      - name: Build
        run: |
          ./gradlew build